---

- name: Raspberry PI bootstrap
  hosts: raspberry
  become: true
  tasks:
    - name: Configure host name
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Configure default user
      user:
        name: pi
        state: present
        groups:
          - sudo
          - docker
        append: true
    - name: Add repositories
      apt_repository:
        state: present
        repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch edge
        update_cache: true
    - name: Install packages
      apt:
        state: latest
        name:
          - netcat
          - docker
          - python-pip
        update_cache: false
    - name: Install python packages
      pip:
        state: latest
        name:
          - docker
          - docker-compose
    - name: Start system services
      service:
        state: started
        enabled: true
        name: "{{ item }}"
      with_items:
        - docker
    - name: Create swarm
      docker_swarm:
        state: present
        advertise_addr: eth0
      when: inventory_hostname == groups['docker-swarm-manager'][0]
      register: swarm_create
    - name: Set manager token variables
      set_fact:
        WORKER_TOKEN: "{{ swarm_create.swarm_facts.JoinTokens.Worker }}"
        MANAGER_TOKEN: "{{ swarm_create.swarm_facts.JoinTokens.Manager }}"
      when: inventory_hostname == groups['docker-swarm-manager'][0]
    - name: Add worker nodes
      docker_swarm:
        state: join
        advertise_addr: eth0
        remote_addrs:
          -  "{{ hostvars[groups['docker-swarm-manager'][0]]['ansible_host'] }}"
        join_token: "{{ hostvars[groups['docker-swarm-manager'][0]]['WORKER_TOKEN'] }}" 
      when: inventory_hostname in groups['docker-swarm-worker']

- name: Deploy components
  hosts: docker-swarm-manager
  become: true
  tasks:
    - name: Create portainer network
      docker_network:
        name: portainer
        driver: overlay
    - name: Deploy portainer agent
      docker_swarm_service:
        name: portainer-agent
        mode: global
        image: portainer/agent
        networks:
          - portainer
        constraints:
          - "node.platform.os == linux"
        env:
          - AGENT_CLUSTER_ADDR=tasks.portainer_agent
        mounts:
          - source: /var/run/docker.sock
            target: /var/run/docker.sock
            type: bind
          - source: /var/lib/docker/volumes
            target: /var/lib/docker/volumes
            type: bind
        update_order: start-first
        update_parallelism: 2
        update_delay: 5
        update_monitor: 500
    - name: Deploy portainer server
      docker_swarm_service:
        name: portainer-server
        mode: replicated
        replicas: 1
        image: portainer/portainer
        args: 
          - "-H" 
          - "tcp://tasks.portainer_agent:9001"
          - "--tlsskipverify"
        networks:
          - portainer
        constraints:
          - "node.role == manager"
        publish:
          - published_port: 9000
            target_port: 9000
            protocol: tcp
        update_order: start-first
        update_parallelism: 2
        update_delay: 5
        update_monitor: 500