---

raspberry:
  vars:
    ansible_ssh_user: pi
    ansible_ssh_pass: raspberry
  hosts:
    rpi-cl-01:
      ansible_host: 192.168.0.101
    rpi-cl-02:
      ansible_host: 192.168.0.102

docker-swarm:
  hosts:
    rpi-cl-01:
    rpi-cl-02:

docker-swarm-manager:
  hosts:
    rpi-cl-01:

docker-swarm-worker:
  hosts:
    rpi-cl-02: